/*
 * This file is generated by jOOQ.
 */
package org.jungmha.infra.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dogs implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer dogId;
    private final String dogImage;
    private final String breedName;
    private final String size;

    public Dogs(Dogs value) {
        this.dogId = value.dogId;
        this.dogImage = value.dogImage;
        this.breedName = value.breedName;
        this.size = value.size;
    }

    public Dogs(
        Integer dogId,
        String dogImage,
        String breedName,
        String size
    ) {
        this.dogId = dogId;
        this.dogImage = dogImage;
        this.breedName = breedName;
        this.size = size;
    }

    /**
     * Getter for <code>public.dogs.dog_id</code>.
     */
    public Integer getDogId() {
        return this.dogId;
    }

    /**
     * Getter for <code>public.dogs.dog_image</code>.
     */
    public String getDogImage() {
        return this.dogImage;
    }

    /**
     * Getter for <code>public.dogs.breed_name</code>.
     */
    public String getBreedName() {
        return this.breedName;
    }

    /**
     * Getter for <code>public.dogs.size</code>.
     */
    public String getSize() {
        return this.size;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Dogs other = (Dogs) obj;
        if (this.dogId == null) {
            if (other.dogId != null)
                return false;
        }
        else if (!this.dogId.equals(other.dogId))
            return false;
        if (this.dogImage == null) {
            if (other.dogImage != null)
                return false;
        }
        else if (!this.dogImage.equals(other.dogImage))
            return false;
        if (this.breedName == null) {
            if (other.breedName != null)
                return false;
        }
        else if (!this.breedName.equals(other.breedName))
            return false;
        if (this.size == null) {
            if (other.size != null)
                return false;
        }
        else if (!this.size.equals(other.size))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.dogId == null) ? 0 : this.dogId.hashCode());
        result = prime * result + ((this.dogImage == null) ? 0 : this.dogImage.hashCode());
        result = prime * result + ((this.breedName == null) ? 0 : this.breedName.hashCode());
        result = prime * result + ((this.size == null) ? 0 : this.size.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dogs (");

        sb.append(dogId);
        sb.append(", ").append(dogImage);
        sb.append(", ").append(breedName);
        sb.append(", ").append(size);

        sb.append(")");
        return sb.toString();
    }
}
