/*
 * This file is generated by jOOQ.
 */
package org.jungmha.infra.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dogwalkerreviews implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer reviewId;
    private final Integer walkerId;
    private final Integer userId;
    private final Integer rating;
    private final String reviewText;

    public Dogwalkerreviews(Dogwalkerreviews value) {
        this.reviewId = value.reviewId;
        this.walkerId = value.walkerId;
        this.userId = value.userId;
        this.rating = value.rating;
        this.reviewText = value.reviewText;
    }

    public Dogwalkerreviews(
        Integer reviewId,
        Integer walkerId,
        Integer userId,
        Integer rating,
        String reviewText
    ) {
        this.reviewId = reviewId;
        this.walkerId = walkerId;
        this.userId = userId;
        this.rating = rating;
        this.reviewText = reviewText;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.review_id</code>.
     */
    public Integer getReviewId() {
        return this.reviewId;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.walker_id</code>.
     */
    public Integer getWalkerId() {
        return this.walkerId;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.rating</code>.
     */
    public Integer getRating() {
        return this.rating;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.review_text</code>.
     */
    public String getReviewText() {
        return this.reviewText;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Dogwalkerreviews other = (Dogwalkerreviews) obj;
        if (this.reviewId == null) {
            if (other.reviewId != null)
                return false;
        }
        else if (!this.reviewId.equals(other.reviewId))
            return false;
        if (this.walkerId == null) {
            if (other.walkerId != null)
                return false;
        }
        else if (!this.walkerId.equals(other.walkerId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.rating == null) {
            if (other.rating != null)
                return false;
        }
        else if (!this.rating.equals(other.rating))
            return false;
        if (this.reviewText == null) {
            if (other.reviewText != null)
                return false;
        }
        else if (!this.reviewText.equals(other.reviewText))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.reviewId == null) ? 0 : this.reviewId.hashCode());
        result = prime * result + ((this.walkerId == null) ? 0 : this.walkerId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.rating == null) ? 0 : this.rating.hashCode());
        result = prime * result + ((this.reviewText == null) ? 0 : this.reviewText.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dogwalkerreviews (");

        sb.append(reviewId);
        sb.append(", ").append(walkerId);
        sb.append(", ").append(userId);
        sb.append(", ").append(rating);
        sb.append(", ").append(reviewText);

        sb.append(")");
        return sb.toString();
    }
}
