version: "3.9"

services:
  jungmhaDB:
    container_name: jungmha-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sql@min
    restart: unless-stopped
    volumes:
      - C:\Items\mysoftwares\JVM\Jungmha\src\main\resources\db\migration:/docker-entrypoint-initdb.d/
