version: "3.9"

services:

  react-vite:
    container_name: react-vite
    image: node:21-alpine
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - ./:/app/source-code
    working_dir: /app/source-code
    command: ["npm", "run", "dev"]
