version: "3.9"

networks:
  dev_network:

services:

  jungmhaDB:
    container_name: jungmha-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sql@min
    volumes:
      - ./Jungmha/src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    networks:
      - dev_network

  jungmha-jit-app:
    container_name: jungmha-jit-app
    image: amazoncorretto:17
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./:/app/source-code
    working_dir: /app/source-code
    command:
      - sh
      - -c
      - |
        chmod +x gradlew;
        ./gradlew assemble;
        java -jar build/docker/optimized/layers/application.jar
    networks:
      - dev_network

  cloudflared-tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiOWY0MTBlZjhhY2ZmYWQzYjY1YmJhNzZiMzQzZjhiZTYiLCJ0IjoiZTk3N2NmYzQtMWJiOS00YjliLTg5NGQtYzA1YWU3NjRjZjZkIiwicyI6IlpUazBObUkwTURndFpqVTROQzAwTnpoakxUazNOMkV0Tm1SaE1qUTBOems1Tm1NeiJ9
