version: "3.9"

networks:
  dev_network:

services:

  jungmhaDB:
    container_name: jungmha-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sql@min
    volumes:
      - /home/rushmi0/items/Software/Kotlin/Jungmha/src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    networks:
      - dev_network

  jungmhaApp:
    container_name: jungmha-jit-app
    image: amazoncorretto:17
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - /home/rushmi0/items/Software/Kotlin/Jungmha:/app/source-code
    working_dir: /app/source-code
    command:
      - sh
      - -c
      - |
        chmod +x gradlew;
        ./gradlew assemble;
        java -jar build/docker/optimized/layers/application.jar
    networks:
      - dev_network

