version: "3.9"

services:

  jungmhaDB:
    container_name: jungmha-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sql@min
    volumes:
      - C:\Items\mysoftwares\JVM\sm\Jungmha\src\main\resources\db\migration:/docker-entrypoint-initdb.d/
    networks:
      - dev_network

  jungmhaApp:
    container_name: jungmha-app
    image: amazoncorretto:17
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - C:\Items\mysoftwares\JVM\sm\Jungmha:/app/source-code
    working_dir: /app/source-code
    command:
      - sh
      - -c
      - |
        chmod +x gradlew;
        ./gradlew assemble;
        java -jar build/docker/main/layers/application.jar
    networks:
      - dev_network

networks:
  dev_network:
