/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample.tables.records;


import nu.studer.sample.tables.Dogwalkerreviews;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DogwalkerreviewsRecord extends UpdatableRecordImpl<DogwalkerreviewsRecord> implements Record5<Integer, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dogwalkerreviews.review_id</code>.
     */
    public DogwalkerreviewsRecord setReviewId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.review_id</code>.
     */
    public Integer getReviewId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.dogwalkerreviews.walker_id</code>.
     */
    public DogwalkerreviewsRecord setWalkerId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.walker_id</code>.
     */
    public Integer getWalkerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.dogwalkerreviews.user_id</code>.
     */
    public DogwalkerreviewsRecord setUserId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.dogwalkerreviews.rating</code>.
     */
    public DogwalkerreviewsRecord setRating(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.dogwalkerreviews.review_text</code>.
     */
    public DogwalkerreviewsRecord setReviewText(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.dogwalkerreviews.review_text</code>.
     */
    public String getReviewText() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Dogwalkerreviews.DOGWALKERREVIEWS.REVIEW_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Dogwalkerreviews.DOGWALKERREVIEWS.WALKER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Dogwalkerreviews.DOGWALKERREVIEWS.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Dogwalkerreviews.DOGWALKERREVIEWS.RATING;
    }

    @Override
    public Field<String> field5() {
        return Dogwalkerreviews.DOGWALKERREVIEWS.REVIEW_TEXT;
    }

    @Override
    public Integer component1() {
        return getReviewId();
    }

    @Override
    public Integer component2() {
        return getWalkerId();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getRating();
    }

    @Override
    public String component5() {
        return getReviewText();
    }

    @Override
    public Integer value1() {
        return getReviewId();
    }

    @Override
    public Integer value2() {
        return getWalkerId();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getRating();
    }

    @Override
    public String value5() {
        return getReviewText();
    }

    @Override
    public DogwalkerreviewsRecord value1(Integer value) {
        setReviewId(value);
        return this;
    }

    @Override
    public DogwalkerreviewsRecord value2(Integer value) {
        setWalkerId(value);
        return this;
    }

    @Override
    public DogwalkerreviewsRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public DogwalkerreviewsRecord value4(Integer value) {
        setRating(value);
        return this;
    }

    @Override
    public DogwalkerreviewsRecord value5(String value) {
        setReviewText(value);
        return this;
    }

    @Override
    public DogwalkerreviewsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DogwalkerreviewsRecord
     */
    public DogwalkerreviewsRecord() {
        super(Dogwalkerreviews.DOGWALKERREVIEWS);
    }

    /**
     * Create a detached, initialised DogwalkerreviewsRecord
     */
    public DogwalkerreviewsRecord(Integer reviewId, Integer walkerId, Integer userId, Integer rating, String reviewText) {
        super(Dogwalkerreviews.DOGWALKERREVIEWS);

        setReviewId(reviewId);
        setWalkerId(walkerId);
        setUserId(userId);
        setRating(rating);
        setReviewText(reviewText);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DogwalkerreviewsRecord
     */
    public DogwalkerreviewsRecord(nu.studer.sample.tables.pojos.Dogwalkerreviews value) {
        super(Dogwalkerreviews.DOGWALKERREVIEWS);

        if (value != null) {
            setReviewId(value.getReviewId());
            setWalkerId(value.getWalkerId());
            setUserId(value.getUserId());
            setRating(value.getRating());
            setReviewText(value.getReviewText());
            resetChangedOnNotNull();
        }
    }
}
