POST http://localhost:8080/api/v1/user/sign-up
Content-Type: application/json

{
  "imageProfile" : "",
  "userName" : "Rushmi0",
  "firstName" : "Watcharapol",
  "lastName" : "Phongwilai",
  "email" : "ph.watcharapol_st@gmail.com",
  "phoneNumber" : "1234567653",
  "authenKey" : "028fda492e3522673b0b0561526e4b1b96b3bdf81484ca5a1db4f30125fc04be54",
  "userType" : "Normal"
}

### SignUpNewAccountTest

POST http://localhost:8080/api/v1/user/sign-up
Content-Type: application/json

{
  "imageProfile" : "img.png",
  "userName" : "Mai",
  "firstName" : "Maina",
  "lastName" : "Isus",
  "email" : "is.Maina@gmail.com",
  "phoneNumber" : "0991857733",
  "authenKey" : "028fda492e3522673b0b0561526e4b1b96b3bdf81484ca5a1db4f30125fc04be54",
  "userType" : "DogWalkers"
}

###

POST http://localhost:8080/api/v1/user/sign-up
Content-Type: application/json

{
  "imageProfile" : "",
  "userName" : "Bitcoin",
  "firstName" : "Satoshi",
  "lastName" : "Nakamoto",
  "email" : "nk.Satoshi@gmail.com",
  "phoneNumber" : "6666657569",
  "authenKey" : "028fda492e3522673b0b0561526e4b1b96b3bdf81484ca5a1db4f30125fc04be54",
  "userType" : "Normal"
}

###

POST http://localhost:8080/api/v1/user/sign-up
Content-Type: application/json

{
  "imageProfile" : "",
  "userName" : "Cardano",
  "firstName" : "Ada",
  "lastName" : "Lovely",
  "email" : "ly.Ada@gmail.com",
  "phoneNumber" : "6666657569",
  "authenKey" : "028fda492e3522673b0b0561526e4b1b96b3bdf81484ca5a1db4f30125fc04be54",
  "userType" : "Normal"
}


###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "identity": "my-user",
  "secret": "secret"
}

###

POST http://localhost:8080/auth/open-channel
Content-Type: application/json

{
  "userName" : "Rushmi0",
  "authenKey" : "028fda492e3522673b0b0561526e4b1b96b3bdf81484ca5a1db4f30125fc04be54"
}


