
# "fullControl": "eyJ1c2VyTmFtZSI6IkF1cmEiLCJwZXJtaXNzaW9uIjoiZnVsbC1jb250cm9sIiwiZXhwIjo4NjQwMDE3MDM2OTI1NzgzNDMsImlhdCI6MTcwMzY5MjY2NDc0Mywic2lnbmF0dXJlIjoiMzA0NDAyMjA3OTQyYTg1NDQyYjE3ZTAyYjUxMjcwOWY1MjZkZjhhYmIyMjJkZWFiNmVhNjAzODY1ZWI1ZTc3YWNhOGRmNWJjMDIyMDM5YmMzZjBhM2MxZGEwMGUyM2FjMjJiMzQ5MmVkYTBiNjk1NGE1ZTBjYzc0MTQ3MTBhN2RiMDIyMzc4MWU3ODYifQ==",
# "viewOnly": "eyJ1c2VyTmFtZSI6IkF1cmEiLCJwZXJtaXNzaW9uIjoidmlldy1vbmx5IiwiZXhwIjo4NjQwMDE3MDM2OTI1Nzg5NzQsImlhdCI6MTcwMzY5MjY2NTM3NCwic2lnbmF0dXJlIjoiMzA0NTAyMjEwMGYwMDIyOGJjNTJjMTNjODg4OGRlNTBiMGVmMGE0OGRjYWRmN2EyODZiMGIyZmEyMzNkYjFkMTg2YmRlYzk3N2YwMjIwMjFiZmY5NzhmMjhhNzRiM2I2NTkxMzI0NDE0ZmE2ZjIzZTk2MzE4MzZiYzYwYWFhYjZhMGI5NDk0YzJkZmJkNyJ9"

POST http://localhost:8080/api/v1/auth/user/booking
Content-Type: application/json
Access-Token: eyJ1c2VyTmFtZSI6IkF1cmEiLCJwZXJtaXNzaW9uIjoiZnVsbC1jb250cm9sIiwiZXhwIjo4NjQwMDE3MDM2MTg1Mzk0MTksImlhdCI6MTcwMzYxODYyNTgxOSwic2lnbmF0dXJlIjoiMzA0NDAyMjAxMWYyYmQyNWVjYzk0ZWE4NGE0Y2JmZjkzNGYxY2Q1YjA0MTFmZWIzYjExMjUyY2JjNzJjMDM1YTI2M2Q1ZWJiMDIyMDdkOGNiN2E0MWFiZjg3YmE4MDVmZmVjNDUxN2VmNTAxODBiOTUwZWNkZmJlMjgwNWY4OWZhYTA1NzhkMTUyOTAifQ==

{
  "walkerID": 2,
  "dogID" : 2,
  "bookingDate" : "2023-11-15",
  "timeStart" : "19:30",
  "timeEnd" : "22:00"
}