GET http://localhost:8080/api/v1/auth/home/filter
Content-Type: application/json
Authorization: eyJ1c2VyTmFtZSI6IkF1cmEiLCJwZXJtaXNzaW9uIjoiZnVsbC1jb250cm9sIiwiZXhwIjoxNzAzNTM0ODg5ODA4LCJpYXQiOjE3MDM1MjYzMzYyMDgsInNpZ25hdHVyZSI6IjMwNDUwMjIxMDA4ZWRmOWJkZTQ2YWFiZTI2ZmQ0NjMyOTg5ODhkNjMyMmZkMDE4NmE1NGM0MWYwYTM3Y2JmY2Y2YjYzN2YyOTlmMDIyMDM2ZjQ0MGI1OTAwMGUwYTMxY2RhYzViZWQxYTFmMWYyYTlmMTVjMWUwMTIyNDU0ZDkzYTY3MWYyNTEwYjk5N2IifQ==

###

GET http://localhost:8080/api/v1/home/filter?veryfi=true
Content-Type: application/json

###

GET http://localhost:8080/api/v1/home/filter?pSmall=50&max=3
Content-Type: application/json

###

GET http://localhost:8080/api/v1/home/filter?location=Park4
Content-Type: application/json