###
GET http://localhost:8080/api/v1/auth/user/dogwalkers
Access-Token: eyJ1c2VyTmFtZSI6IlJ1c2htaTAiLCJwZXJtaXNzaW9uIjoidmlldyIsImV4cCI6ODY0MDAwMDAwMDE3MDU0MTM1NTM4MDQsImlhdCI6MTcwNTQxMzY0MDIwNCwic2lnbmF0dXJlIjoiMzA0NDAyMjA0NWZjOTMyNmUxZTJlMWFlNjliNTM2MmQ4Yjk0ZDI5NDI1MDlmYTJhNGRkODQwZGUwMDg1Y2RlOTBkODY4ZTFjMDIyMDUyNTlhOTIwODcwMGRjZDg1YzFjOWU2NDUyOWJhZjJlZjZhNzBkOTBhYjZhN2UzMmMwZWIwYzE1NmExNzRmMDMifQ==

