GET http://localhost:8080/api/v1/auth/user/normal/user3
Access-Token: eyJ1c2VyTmFtZSI6IkF1cmEiLCJwZXJtaXNzaW9uIjoidmlldyIsImV4cCI6ODY0MDAwMDAwMDE3MDM5NjUzOTgzMjYsImlhdCI6MTcwMzk2NTQ4NDcyNiwic2lnbmF0dXJlIjoiMzA0NDAyMjAzZjZlN2JjNDk0ZWMyMTdhNTc5NzQ0YWI4MzNlMTE1NTQ5MmJiODk3ZmE1MmU0MTQ4ODVhNDYxYmQwOGNjMDU4MDIyMDQzNGUwNzQ5MmI0MmRhMmRmNDI5YTM2MWZhOTU0ZWU0YzVkZTI0OTliODVmNDc2ZWU2NzI4MGUyMGE1MTMwMjEifQ==