### User 1
PUT http://localhost:8080/api/v1/auth/sign-up
Content-Type: application/json
UserName: Aura

{
  "content" : "JYg/JtU7Mc7J6IFEjayEqSY9N1qtjhuBqM11jt4isK6foIW36ePNm5p2861b2GGEmiWf5Fqqlz2Db/j1Kz9MOnkZZfdM4yJi1trq54Q5A7p0M6dUrvCKibx5386l4XZZjtYRsFDpUajh3BJ9+E1KppjgjdN/+pLz2mMHes99mBbEjmixgHb11irI?iv=AAAAAAAAAAAAAAAA"
}


### User 2
PUT http://localhost:8080/api/v1/auth/sign-up
Content-Type: application/json
UserName: Rushmi0

{
  "content": "PWFTdAu0KqHpJhN1AmU60iVmJg/zWhu5rL9sVHsFGBeJ84RYidfOiCLZIPuJLtfXJps0FeqqSIOPYyx8eW2IniqnLpSfyQ8zxa6ljlJLJ5Ek/2l1sO01ZDonltmCccwGTe1GwHvTrNO2EOP/CnmAJsppNpCD3AGD/sj2+u+HV39xEPJETCDyG8muadZLUx+k?iv=XNJhr8omGp5W0AMZA3vJRg=="
}



