/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample;


import nu.studer.sample.tables.Dogwalkerreviews;
import nu.studer.sample.tables.FlywaySchemaHistory;
import nu.studer.sample.tables.Userprofiles;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_REVIEWS_USERID = Internal.createIndex(DSL.name("idx_reviews_userid"), Dogwalkerreviews.DOGWALKERREVIEWS, new OrderField[] { Dogwalkerreviews.DOGWALKERREVIEWS.USER_ID }, false);
    public static final Index IDX_REVIEWS_WALKERID = Internal.createIndex(DSL.name("idx_reviews_walkerid"), Dogwalkerreviews.DOGWALKERREVIEWS, new OrderField[] { Dogwalkerreviews.DOGWALKERREVIEWS.WALKER_ID }, false);
    public static final Index IDX_USERS_EMAIL = Internal.createIndex(DSL.name("idx_users_email"), Userprofiles.USERPROFILES, new OrderField[] { Userprofiles.USERPROFILES.EMAIL }, false);
    public static final Index IDX_USERS_PUBLIC_KEY = Internal.createIndex(DSL.name("idx_users_public_key"), Userprofiles.USERPROFILES, new OrderField[] { Userprofiles.USERPROFILES.AUTHEN_KEY }, false);
}
