/*
 * This file is generated by jOOQ.
 */
package nu.studer.sample;


import java.util.Arrays;
import java.util.List;

import nu.studer.sample.tables.Dogs;
import nu.studer.sample.tables.Dogwalkbookings;
import nu.studer.sample.tables.Dogwalkerreviews;
import nu.studer.sample.tables.Dogwalkers;
import nu.studer.sample.tables.FlywaySchemaHistory;
import nu.studer.sample.tables.Userprofiles;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.dogs</code>.
     */
    public final Dogs DOGS = Dogs.DOGS;

    /**
     * The table <code>public.dogwalkbookings</code>.
     */
    public final Dogwalkbookings DOGWALKBOOKINGS = Dogwalkbookings.DOGWALKBOOKINGS;

    /**
     * The table <code>public.dogwalkerreviews</code>.
     */
    public final Dogwalkerreviews DOGWALKERREVIEWS = Dogwalkerreviews.DOGWALKERREVIEWS;

    /**
     * The table <code>public.dogwalkers</code>.
     */
    public final Dogwalkers DOGWALKERS = Dogwalkers.DOGWALKERS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.userprofiles</code>.
     */
    public final Userprofiles USERPROFILES = Userprofiles.USERPROFILES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Dogs.DOGS,
            Dogwalkbookings.DOGWALKBOOKINGS,
            Dogwalkerreviews.DOGWALKERREVIEWS,
            Dogwalkers.DOGWALKERS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Userprofiles.USERPROFILES
        );
    }
}
