/*
 * This file is generated by jOOQ.
 */
package org.jungmha.infra.database;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jungmha.infra.database.tables.Dogs;
import org.jungmha.infra.database.tables.Dogwalkbookings;
import org.jungmha.infra.database.tables.Dogwalkerreviews;
import org.jungmha.infra.database.tables.Dogwalkers;
import org.jungmha.infra.database.tables.FlywaySchemaHistory;
import org.jungmha.infra.database.tables.Userprofiles;
import org.jungmha.infra.database.tables.records.DogsRecord;
import org.jungmha.infra.database.tables.records.DogwalkbookingsRecord;
import org.jungmha.infra.database.tables.records.DogwalkerreviewsRecord;
import org.jungmha.infra.database.tables.records.DogwalkersRecord;
import org.jungmha.infra.database.tables.records.FlywaySchemaHistoryRecord;
import org.jungmha.infra.database.tables.records.UserprofilesRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DogsRecord> DOGS_PKEY = Internal.createUniqueKey(Dogs.DOGS, DSL.name("dogs_pkey"), new TableField[] { Dogs.DOGS.DOG_ID }, true);
    public static final UniqueKey<DogwalkbookingsRecord> DOGWALKBOOKINGS_PKEY = Internal.createUniqueKey(Dogwalkbookings.DOGWALKBOOKINGS, DSL.name("dogwalkbookings_pkey"), new TableField[] { Dogwalkbookings.DOGWALKBOOKINGS.BOOKING_ID }, true);
    public static final UniqueKey<DogwalkerreviewsRecord> DOGWALKERREVIEWS_PKEY = Internal.createUniqueKey(Dogwalkerreviews.DOGWALKERREVIEWS, DSL.name("dogwalkerreviews_pkey"), new TableField[] { Dogwalkerreviews.DOGWALKERREVIEWS.REVIEW_ID }, true);
    public static final UniqueKey<DogwalkersRecord> DOGWALKERS_PKEY = Internal.createUniqueKey(Dogwalkers.DOGWALKERS, DSL.name("dogwalkers_pkey"), new TableField[] { Dogwalkers.DOGWALKERS.WALKER_ID }, true);
    public static final UniqueKey<DogwalkersRecord> DOGWALKERS_USER_ID_KEY = Internal.createUniqueKey(Dogwalkers.DOGWALKERS, DSL.name("dogwalkers_user_id_key"), new TableField[] { Dogwalkers.DOGWALKERS.USER_ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<UserprofilesRecord> USERPROFILES_EMAIL_KEY = Internal.createUniqueKey(Userprofiles.USERPROFILES, DSL.name("userprofiles_email_key"), new TableField[] { Userprofiles.USERPROFILES.EMAIL }, true);
    public static final UniqueKey<UserprofilesRecord> USERPROFILES_PHONE_NUMBER_KEY = Internal.createUniqueKey(Userprofiles.USERPROFILES, DSL.name("userprofiles_phone_number_key"), new TableField[] { Userprofiles.USERPROFILES.PHONE_NUMBER }, true);
    public static final UniqueKey<UserprofilesRecord> USERPROFILES_PKEY = Internal.createUniqueKey(Userprofiles.USERPROFILES, DSL.name("userprofiles_pkey"), new TableField[] { Userprofiles.USERPROFILES.USER_ID }, true);
    public static final UniqueKey<UserprofilesRecord> USERPROFILES_USERNAME_KEY = Internal.createUniqueKey(Userprofiles.USERPROFILES, DSL.name("userprofiles_username_key"), new TableField[] { Userprofiles.USERPROFILES.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DogwalkbookingsRecord, DogsRecord> DOGWALKBOOKINGS__DOGWALKBOOKINGS_DOG_ID_FKEY = Internal.createForeignKey(Dogwalkbookings.DOGWALKBOOKINGS, DSL.name("dogwalkbookings_dog_id_fkey"), new TableField[] { Dogwalkbookings.DOGWALKBOOKINGS.DOG_ID }, Keys.DOGS_PKEY, new TableField[] { Dogs.DOGS.DOG_ID }, true);
    public static final ForeignKey<DogwalkbookingsRecord, UserprofilesRecord> DOGWALKBOOKINGS__DOGWALKBOOKINGS_USER_ID_FKEY = Internal.createForeignKey(Dogwalkbookings.DOGWALKBOOKINGS, DSL.name("dogwalkbookings_user_id_fkey"), new TableField[] { Dogwalkbookings.DOGWALKBOOKINGS.USER_ID }, Keys.USERPROFILES_PKEY, new TableField[] { Userprofiles.USERPROFILES.USER_ID }, true);
    public static final ForeignKey<DogwalkbookingsRecord, DogwalkersRecord> DOGWALKBOOKINGS__DOGWALKBOOKINGS_WALKER_ID_FKEY = Internal.createForeignKey(Dogwalkbookings.DOGWALKBOOKINGS, DSL.name("dogwalkbookings_walker_id_fkey"), new TableField[] { Dogwalkbookings.DOGWALKBOOKINGS.WALKER_ID }, Keys.DOGWALKERS_PKEY, new TableField[] { Dogwalkers.DOGWALKERS.WALKER_ID }, true);
    public static final ForeignKey<DogwalkerreviewsRecord, UserprofilesRecord> DOGWALKERREVIEWS__DOGWALKERREVIEWS_USER_ID_FKEY = Internal.createForeignKey(Dogwalkerreviews.DOGWALKERREVIEWS, DSL.name("dogwalkerreviews_user_id_fkey"), new TableField[] { Dogwalkerreviews.DOGWALKERREVIEWS.USER_ID }, Keys.USERPROFILES_PKEY, new TableField[] { Userprofiles.USERPROFILES.USER_ID }, true);
    public static final ForeignKey<DogwalkerreviewsRecord, DogwalkersRecord> DOGWALKERREVIEWS__DOGWALKERREVIEWS_WALKER_ID_FKEY = Internal.createForeignKey(Dogwalkerreviews.DOGWALKERREVIEWS, DSL.name("dogwalkerreviews_walker_id_fkey"), new TableField[] { Dogwalkerreviews.DOGWALKERREVIEWS.WALKER_ID }, Keys.DOGWALKERS_PKEY, new TableField[] { Dogwalkers.DOGWALKERS.WALKER_ID }, true);
    public static final ForeignKey<DogwalkersRecord, UserprofilesRecord> DOGWALKERS__DOGWALKERS_USER_ID_FKEY = Internal.createForeignKey(Dogwalkers.DOGWALKERS, DSL.name("dogwalkers_user_id_fkey"), new TableField[] { Dogwalkers.DOGWALKERS.USER_ID }, Keys.USERPROFILES_PKEY, new TableField[] { Userprofiles.USERPROFILES.USER_ID }, true);
}
