/*
 * This file is generated by jOOQ.
 */
package org.jungmha.infra.database;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jungmha.infra.database.tables.Dogs;
import org.jungmha.infra.database.tables.Dogwalkbookings;
import org.jungmha.infra.database.tables.Dogwalkerreviews;
import org.jungmha.infra.database.tables.Dogwalkers;
import org.jungmha.infra.database.tables.Userprofiles;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.dogs</code>.
     */
    public final Dogs DOGS = Dogs.DOGS;

    /**
     * The table <code>public.dogwalkbookings</code>.
     */
    public final Dogwalkbookings DOGWALKBOOKINGS = Dogwalkbookings.DOGWALKBOOKINGS;

    /**
     * The table <code>public.dogwalkerreviews</code>.
     */
    public final Dogwalkerreviews DOGWALKERREVIEWS = Dogwalkerreviews.DOGWALKERREVIEWS;

    /**
     * The table <code>public.dogwalkers</code>.
     */
    public final Dogwalkers DOGWALKERS = Dogwalkers.DOGWALKERS;

    /**
     * The table <code>public.userprofiles</code>.
     */
    public final Userprofiles USERPROFILES = Userprofiles.USERPROFILES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Dogs.DOGS,
            Dogwalkbookings.DOGWALKBOOKINGS,
            Dogwalkerreviews.DOGWALKERREVIEWS,
            Dogwalkers.DOGWALKERS,
            Userprofiles.USERPROFILES
        );
    }
}
