/*
 * This file is generated by jOOQ.
 */
package org.jungmha.infra.database;


import org.jungmha.infra.database.tables.Dogs;
import org.jungmha.infra.database.tables.Dogwalkbookings;
import org.jungmha.infra.database.tables.Dogwalkerreviews;
import org.jungmha.infra.database.tables.Dogwalkers;
import org.jungmha.infra.database.tables.Userprofiles;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.dogs</code>.
     */
    public static final Dogs DOGS = Dogs.DOGS;

    /**
     * The table <code>public.dogwalkbookings</code>.
     */
    public static final Dogwalkbookings DOGWALKBOOKINGS = Dogwalkbookings.DOGWALKBOOKINGS;

    /**
     * The table <code>public.dogwalkerreviews</code>.
     */
    public static final Dogwalkerreviews DOGWALKERREVIEWS = Dogwalkerreviews.DOGWALKERREVIEWS;

    /**
     * The table <code>public.dogwalkers</code>.
     */
    public static final Dogwalkers DOGWALKERS = Dogwalkers.DOGWALKERS;

    /**
     * The table <code>public.userprofiles</code>.
     */
    public static final Userprofiles USERPROFILES = Userprofiles.USERPROFILES;
}
