name: Backend Compile and Test

on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      jungmhaDB:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: sql@min

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          vendor: 'graal'
          cache: 'gradle'

      - name: Build and Test with GraalVM
        run: |
          ./gradlew build
          ./gradlew test

      - name: Compile with GraalVM
        run: |
          chmod +x run_aot_app.sh
          ./run_aot_app.sh

