name: Build and Run Native Image

on:
  push:
    branches:
      - backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      jungmhaDB:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: sql@min
        ports:
          - 5432:5432


    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build and compile with GraalVM
        run: |
          docker compose up -d jungmhaDB
          docker compose up -d jungmha-native-image

      - name: Run JVM application
        run: |
          docker compose up -d jungmha-jvm-app
