name: GraalVM CE 17 Build

on:
  push:
    branches:
      - backend

jobs:
  build-and-compile:
    runs-on: ubuntu-latest

    services:
      jungmhaDB:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: sql@min
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: actions/setup-java@v2
        with:
          distribution: 'graalvm-ce'
          java-version: '17'

      - name: Build and compile with GraalVM
        run: |
          chmod +x run_aot_app.sh
          ./run_aot_app.sh
        working-directory: ./source-code