name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - backend-test

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIzZWRtRCIsInByb2plY3QiOiJBTGFLTCIsInRva2VuIjoiM0tkRFIifQ.y439EMOyn_Dj9VQ5-xycWhkjwIc24jqXIv3CM8HNvFg